version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  build-and-test:
    docker:
      - image: faiello1999/simdata-tables
    steps:
      - run:
          command: python3 -m unittest
          name: test
      - run:
          command: python3 main.py
          name: build
      - codecov/upload:
          file: .coverage
      

workflows:
  main:
    jobs:
      - build-and-test
