jobs:
  build:
    executor: python3/default
    steps:
      - checkout
      - python3/load-cache
      - python3/install-deps
      - python3/save-cache
      - run:
          command: |
            # pytest would be a dep in requirements.txt
            python -m unittest
          name: Test
orbs:
  python: circleci/python@0.1
version: 2.1
workflows:
  main:
    jobs:
      - build