version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run: python3 -m venv env
      - run: source ./env/bin/activate 
      - run: sudo pip3 install -r requirements.txt
      - run: python -m unittest